"""Keyboards package."""
from backend.app.bot.keyboards.keyboards import (
    area_keyboard,
    back_to_menu_keyboard,
    courts_keyboard,
    fpm_after_select_keyboard,
    fpm_card_keyboard,
    fpm_empty_keyboard,
    fpm_selected_list_keyboard,
    invitation_keyboard,
    language_keyboard,
    main_menu_keyboard,
    om_confirm_keyboard,
    om_court_keyboard,
    om_date_keyboard,
    om_level_keyboard,
    om_players_keyboard,
    om_success_keyboard,
    om_time_keyboard,
    partner_actions_keyboard,
    settings_keyboard,
    skill_level_keyboard,
)

__all__ = [
    "language_keyboard",
    "skill_level_keyboard",
    "area_keyboard",
    "courts_keyboard",
    "main_menu_keyboard",
    "partner_actions_keyboard",
    "settings_keyboard",
    "back_to_menu_keyboard",
    "om_date_keyboard",
    "om_time_keyboard",
    "om_court_keyboard",
    "om_level_keyboard",
    "om_players_keyboard",
    "om_confirm_keyboard",
    "om_success_keyboard",
    "fpm_card_keyboard",
    "fpm_after_select_keyboard",
    "fpm_selected_list_keyboard",
    "fpm_empty_keyboard",
    "invitation_keyboard",
]
