"""add round and winner_player_id to games

Revision ID: e417d3f7d1a4
Revises: 9c75a6368f08
Create Date: 2026-07-09 17:13:50.800178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e417d3f7d1a4'
down_revision: Union[str, None] = '9c75a6368f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('winner_player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_games_winner_player_id_players', 'players', ['winner_player_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_winner_player_id_players', type_='foreignkey')
        batch_op.drop_column('winner_player_id')
        batch_op.drop_column('round')

    # ### end Alembic commands ###
