"""add operator_permissions and admin_audit_logs tables

Revision ID: f0f6e3703ad9
Revises: d1cb7b878c4c
Create Date: 2026-07-03 20:43:52.186818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f6e3703ad9'
down_revision: Union[str, None] = 'd1cb7b878c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('operator_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('MODERATOR', 'ADMIN', 'OWNER', name='operatorrole'), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_permissions_telegram_id'), ['telegram_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_permissions_telegram_id'))

    op.drop_table('operator_permissions')
    # Explicit drop for Postgres, where sa.Enum creates a real TYPE that
    # dropping the table alone does not remove. No-op on SQLite.
    sa.Enum(name='operatorrole').drop(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_action'))

    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
