"""Tournament and TournamentPlayer ORM models (Sprint 12 — Tournament
Platform v1, Phase 1).

Tournament matches are NOT a new entity — they are ordinary Game rows
(Game.tournament_id) generated by TournamentService.generate_matches(),
reusing GameService/MatchLifecycleService unchanged. Only registration
and the tournament's own lifecycle live here.
"""
import enum
from datetime import date, datetime, time

from sqlalchemy import Date, DateTime, Enum, ForeignKey, Integer, String, Text, Time
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from backend.app.database.base import Base


class TournamentStatus(str, enum.Enum):
    DRAFT = "draft"
    REGISTRATION_OPEN = "registration_open"
    REGISTRATION_CLOSED = "registration_closed"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class TournamentPlayerStatus(str, enum.Enum):
    REGISTERED = "registered"
    WITHDRAWN = "withdrawn"


class Tournament(Base):
    """A tournament an Admin or Verified Coach organizes; players
    register/withdraw, then Generate Matches creates ordinary Games."""

    __tablename__ = "tournaments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    organizer_player_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("players.id", ondelete="CASCADE"), nullable=False
    )

    area: Mapped[str] = mapped_column(String(64), nullable=False)
    court: Mapped[str] = mapped_column(String(256), nullable=False)
    start_date: Mapped[date] = mapped_column(Date, nullable=False)
    start_time: Mapped[time] = mapped_column(Time, nullable=False)
    registration_deadline: Mapped[date] = mapped_column(Date, nullable=False)
    max_players: Mapped[int] = mapped_column(Integer, nullable=False)

    status: Mapped[TournamentStatus] = mapped_column(
        Enum(TournamentStatus), default=TournamentStatus.DRAFT, nullable=False
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    organizer: Mapped["Player"] = relationship("Player")  # noqa: F821
    registrations: Mapped[list["TournamentPlayer"]] = relationship(
        "TournamentPlayer", back_populates="tournament", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Tournament id={self.id} name={self.name!r} status={self.status}>"


class TournamentPlayer(Base):
    """Association between a Tournament and a registered Player —
    structural mirror of GamePlayer."""

    __tablename__ = "tournament_players"

    tournament_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("tournaments.id", ondelete="CASCADE"), primary_key=True
    )
    player_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("players.id", ondelete="CASCADE"), primary_key=True
    )
    status: Mapped[TournamentPlayerStatus] = mapped_column(
        Enum(TournamentPlayerStatus), default=TournamentPlayerStatus.REGISTERED, nullable=False
    )
    registered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    tournament: Mapped["Tournament"] = relationship("Tournament", back_populates="registrations")
    player: Mapped["Player"] = relationship("Player")  # noqa: F821

    def __repr__(self) -> str:
        return (
            f"<TournamentPlayer tournament_id={self.tournament_id} "
            f"player_id={self.player_id} status={self.status}>"
        )
